#!/usr/bin/env python3
"""MacControl signed-OTA tool (spec 15.3).

Container format (the device contract — do not change without changing
src/ota.cpp and the AT-12 expectations):

    image.ota = 64-byte raw ECDSA P-256 signature (r || s, each 32 bytes
                big-endian, zero-padded) || firmware image bytes

The signature is computed over the SHA-256 digest of the IMAGE portion only.
The device streams the container to the inactive OTA slot, hashes the image
incrementally, and verifies this signature against the public key compiled
into the firmware (firmware/src/ota_pubkey.h, generated by the `pubheader`
command) BEFORE reporting success; a failed verify aborts the slot write.

The firmware image carries a 36-byte version marker (see
lib/maccontrol_core/mc_ota.h — magic "MCV1" + 32-byte version string) that
the device scans for in the freshly written slot so the upload response can
report the target version truthfully; sign/verify print it host-side too.

Usage:
    ota_sign.py keygen --out <prefix>
        Writes <prefix>.pem (SECP256R1 private key, PEM, PKCS#8, unencrypted)
        and <prefix>.pub.hex (lowercase hex of the standard 0x04-prefixed
        65-byte uncompressed point, for embedding in firmware).

    ota_sign.py sign --key <prefix>.pem --in firmware.bin --out image.ota
        Writes the signed container and prints the image version marker.

    ota_sign.py verify --pub <prefix>.pub.hex --in image.ota
        Host-side check; exit 0 on valid signature, 1 otherwise.

    ota_sign.py pubheader --key <prefix>.pem --out src/ota_pubkey.h \
        [--name kOtaPublicKeyDev]
        Generates the firmware header with the compiled-in public key.

Keys under keys/ are DEVELOPMENT keys committed to the repo. Production
devices MUST generate and embed their own key (see keys/README.md).
"""

import argparse
import sys

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import (
        decode_dss_signature,
        encode_dss_signature,
    )
except ImportError:  # pragma: no cover - environment hint
    sys.stderr.write(
        "error: the 'cryptography' package is required "
        "(install it into firmware/.venv: ./.venv/bin/pip install cryptography)\n"
    )
    sys.exit(2)

SIG_LEN = 64
MARKER_MAGIC = b"MCV1"
MARKER_VERSION_LEN = 32


def load_private_key(path):
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def public_point_bytes(key):
    return key.public_key().public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    )


def find_version_marker(image):
    """Return the embedded firmware version string, or None."""
    off = image.find(MARKER_MAGIC)
    while off != -1:
        raw = image[off + 4 : off + 4 + MARKER_VERSION_LEN]
        ver = raw.split(b"\0", 1)[0]
        if ver and all(32 <= b < 127 for b in ver):
            return ver.decode("ascii")
        off = image.find(MARKER_MAGIC, off + 1)
    return None


def cmd_keygen(args):
    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    with open(args.out + ".pem", "wb") as f:
        f.write(pem)
    point = public_point_bytes(key)
    with open(args.out + ".pub.hex", "w") as f:
        f.write(point.hex() + "\n")
    print(f"wrote {args.out}.pem and {args.out}.pub.hex ({len(point)}-byte point)")
    return 0


def cmd_sign(args):
    key = load_private_key(args.key)
    with open(args.in_path, "rb") as f:
        image = f.read()
    if len(image) == 0:
        sys.stderr.write("error: empty firmware image\n")
        return 1
    der = key.sign(image, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    sig = r.to_bytes(32, "big") + s.to_bytes(32, "big")
    with open(args.out, "wb") as f:
        f.write(sig)
        f.write(image)
    ver = find_version_marker(image)
    print(f"wrote {args.out} ({SIG_LEN + len(image)} bytes)")
    print(f"image version: {ver if ver else '(no MCV1 marker found)'}")
    return 0


def cmd_verify(args):
    with open(args.pub, "r") as f:
        point = bytes.fromhex(f.read().strip())
    if len(point) != 65 or point[0] != 0x04:
        sys.stderr.write("error: public key must be a 0x04-prefixed 65-byte point\n")
        return 1
    pub = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), point)
    with open(args.in_path, "rb") as f:
        container = f.read()
    if len(container) < SIG_LEN + 1:
        sys.stderr.write("error: container too small for signature + image\n")
        return 1
    sig, image = container[:SIG_LEN], container[SIG_LEN:]
    r = int.from_bytes(sig[:32], "big")
    s = int.from_bytes(sig[32:], "big")
    try:
        pub.verify(encode_dss_signature(r, s), image, ec.ECDSA(hashes.SHA256()))
    except Exception:
        sys.stderr.write("VERIFY FAILED: signature invalid for this image/key\n")
        return 1
    ver = find_version_marker(image)
    print(f"VERIFY OK ({len(image)}-byte image"
          + (f", version {ver}" if ver else "") + ")")
    return 0


def cmd_pubheader(args):
    key = load_private_key(args.key)
    point = public_point_bytes(key)
    bytes_per_row = 13
    rows = [point[i : i + bytes_per_row] for i in range(0, len(point), bytes_per_row)]
    body = "\n".join(
        "    " + ", ".join(f"0x{b:02x}" for b in row) + "," for row in rows
    )
    text = f"""// GENERATED FILE — produced by scripts/ota_sign.py pubheader. Do not edit.
// Regenerate: ./.venv/bin/python scripts/ota_sign.py pubheader \\
//     --key keys/ota_dev.pem --out src/ota_pubkey.h
//
// MacControl OTA signing key (ECDSA P-256 / SECP256R1, uncompressed point,
// 0x04-prefixed). This is the DEVELOPMENT key committed under keys/ — it is
// public knowledge by design. PRODUCTION DEVICES MUST embed their own key
// (regenerate with `ota_sign.py keygen` and replace this header).
#pragma once
#include <cstdint>

inline constexpr uint8_t {args.name}[65] = {{
{body}
}};
"""
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out}")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("keygen", help="generate a signing key pair")
    p.add_argument("--out", required=True, help="output prefix")
    p.set_defaults(func=cmd_keygen)

    p = sub.add_parser("sign", help="sign a firmware image")
    p.add_argument("--key", required=True, help="private key (.pem)")
    p.add_argument("--in", dest="in_path", required=True, help="firmware.bin")
    p.add_argument("--out", required=True, help="signed container (.ota)")
    p.set_defaults(func=cmd_sign)

    p = sub.add_parser("verify", help="verify a signed container host-side")
    p.add_argument("--pub", required=True, help="public key (.pub.hex)")
    p.add_argument("--in", dest="in_path", required=True, help="signed container")
    p.set_defaults(func=cmd_verify)

    p = sub.add_parser("pubheader", help="generate the firmware public-key header")
    p.add_argument("--key", required=True, help="private key (.pem)")
    p.add_argument("--out", required=True, help="header output path")
    p.add_argument("--name", default="kOtaPublicKeyDev", help="C array name")
    p.set_defaults(func=cmd_pubheader)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
