#pragma once
#include <cstdint>
#include <string>
#include "mc_clock.h"
#include "mc_random.h"

namespace mcco {

// Pairing lifecycle (spec 3.2.2). unpaired -> pairing_window -> active ->
// revoked -> unpaired (record purged 30 days after revocation). At most one
// record is `active` at any time; completing a new ceremony implicitly
// revokes the incumbent.
enum class PairingState : uint8_t { Unpaired, PairingWindow, Active, Revoked };

const char* pairing_state_to_string(PairingState s);
bool pairing_state_from_string(const char* s, PairingState& out);

// Stored pairing record (spec 3.2.2 schema). The raw agent_token is never
// stored — only its SHA-256 hex digest.
struct PairingRecord {
    std::string pairing_id;          // "pr-" + 6 hex
    std::string device_id;           // 12 hex, this endpoint
    std::string agent_instance_id;   // "ag-XXXX", generated by the MCA
    std::string token_sha256;        // 64 lowercase hex chars
    uint64_t created_at = 0;         // epoch seconds
    uint64_t last_used_at = 0;       // epoch seconds
};

enum class PairCodeResult : uint8_t {
    Ok,            // code accepted; call completePairing() next
    WrongCode,     // failed attempt counted (window may have just closed)
    RateLimited,   // >1 attempt in the same second (spec 3.2.1); not counted
    NoWindow       // no open window (409 agent_not_paired)
};

class PairingStore {
public:
    PairingStore(IRandom& rng, IClock& clock, std::string device_id);

    PairingState state() const;
    bool paired() const { return state() == PairingState::Active; }

    // Window: default lifetime 120 s, configurable 60-600 s (spec 3.2.1).
    // Closes any existing window and generates a fresh one-time code.
    // Interval arithmetic uses the MONOTONIC clock: epoch time can jump
    // forward when SNTP first syncs after boot (the pre-sync fallback
    // timeline starts at 2025-01-01), which would otherwise insta-expire a
    // freshly opened window.
    bool openWindow(uint32_t duration_s);
    void closeWindow();
    bool windowOpen() const;
    const std::string& pairingCode() const { return code_; }
    uint32_t windowSecondsRemaining() const;
    uint32_t windowFailedAttempts() const { return failed_; }

    // One validation attempt. Rate-limited attempts are rejected but do not
    // count toward the 5-failure window close (spec 3.2.1).
    PairCodeResult validateCode(const std::string& code);

    // After validateCode returned Ok: atomically store the pairing record
    // (revoking any incumbent) and close the window. Returns the raw agent
    // token (base64url, 32 bytes) to hand to the MCA exactly once.
    std::string completePairing(const std::string& agent_instance_id);

    // ADMIN revocation (spec 3.2.2). Immediate; returns false if not active.
    bool revoke();

    // Evidence admission (spec 2.2.2): token digest + instance id match.
    bool tokenMatches(const std::string& raw_token_b64url) const;
    // True if the presented token's digest matches the stored record even
    // when the record is not active (spec 4.3.1: a known but revoked
    // credential is 403 forbidden, not 401).
    bool tokenDigestKnown(const std::string& raw_token_b64url) const;
    bool instanceMatches(const std::string& agent_instance_id) const;
    void touchLastUsed();

    const PairingRecord* activeRecord() const;

    // Persistence glue (double-slot NVS record), mirrors KeyStore split.
    std::string dump() const;       // JSON document
    bool restore(const std::string& json);

    static constexpr uint32_t kDefaultWindowS = 120;
    static constexpr uint32_t kMinWindowS = 60;
    static constexpr uint32_t kMaxWindowS = 600;
    static constexpr uint32_t kMaxFailedAttempts = 5;
    static constexpr uint32_t kAttemptIntervalS = 1;
    static constexpr uint64_t kRevokedRetentionS = 30ULL * 24 * 3600;

private:
    void expireWindowIfNeeded();
    void purgeRevokedIfNeeded();

    IRandom& rng_;
    IClock& clock_;
    std::string device_id_;
    PairingState state_ = PairingState::Unpaired;
    PairingRecord record_;
    std::string code_;               // valid only while state_ == PairingWindow
    uint32_t window_duration_s_ = 0;
    uint64_t window_opened_ms_ = 0;  // monotonic (millis)
    uint64_t last_attempt_ms_ = 0;   // monotonic (millis)
    bool has_attempted_ = false;
    uint32_t failed_ = 0;
    uint64_t revoked_at_ = 0;        // epoch seconds (persisted/display)
};

} // namespace mcco
